#错误

---

`try` 语句使您能够测试代码块中的错误。

`catch` 语句允许您处理错误。

`throw` 语句允许您创建自定义错误。

`finally` 使您能够执行代码，在 `try` 和 `catch` 之后，无论结果如何

```javascript
try {
    adddlert("欢迎您，亲爱的用户！");
}
catch(err) {
    // err这个错误对象带有name和message两个属性
    throw(err.name + "---" + err.message);
}
finally {
    alert("执行完毕")
}
```